SELECT TEMP1.SN
FROM (SELECT S.ID SI,S.NAME SN,P.SALARY PS FROM STUDENTS S JOIN PACKAGES P ON S.ID=P.ID) TEMP1 JOIN (SELECT FF.ID FI,FF.FRIEND_ID FD,PP.SALARY PPS FROM FRIENDS FF JOIN PACKAGES PP ON FF.FRIEND_ID=PP.ID) TEMP2 ON TEMP1.SI=TEMP2.FI AND TEMP1.PS<TEMP2.PPS
ORDER BY TEMP2.PPS ASC;